---
- name: Deploy image
  hosts: "dev"
  become: true
  ignore_errors: yes
  gather_facts: false

  pre_tasks:

   - name: pull an image 18.217.56.29:8082/java
     shell: "docker login -u admin -p kalyan 18.217.56.29:8082/repository/java/ && docker pull 18.217.56.29:8082/java"
     register: deployStatus
   - shell: "docker rm -f spacegame"
   - shell: "docker run -d --name spacegame -p 8081:80  18.217.56.29:8082/java"
